public with sharing class MembershipConstants {
    public static final String NONE = 'NONE';

    public static final String PENDING = 'PENDING';

    public static final String ACTIVE = 'ACTIVE';

    public static final String REJECTED = 'REJECTED';

    public static final String APPROVED = 'Approved';

    public static final String CANCELLED = 'Cancelled';



    public MembershipConstants() {

    }
}